#!/bin/bash
export HSA_XNACK=0
#module purge                                                                                                                                                                                                    
module load LUMI/23.09                                                                                                                                                                                          
module load partition/G

module load cce/16.0.1

#module load PrgEnv-cray                                                                                                                                                                                         
module load rocm/5.4.6                                                                                                                                   
#module load cray-libsci

#module load cray-hdf5/1.12.2.7                                                                                                                                                                                  
#module load cray-netcdf/4.9.0.7 
